#!/bin/bash
# Hugo GUTEKUNST
# A wrapper to manage easily SSH with a server list
# You shoud add these commands to your ".bashrc" file to enable "alias" and "auto-completion" from a ${serverList} :
# ---
#	serverList="/home/${USER}/Documents/servers.list"
#	complete -W "$(cat ${serverList})" ssr
#	alias ssr='/home/${USER}/Scripts/ssr' 

tabTitle="${1}"
sshUser='root'
sshKeyPath="/home/${USER}/.ssh/hugo_gutekunst"

if [ $# -eq 0 ]; then echo -e "* USAGE :\t${0} [server.fqdn.tld]" && exit 100 ; fi
if [ $(ssh-add -l | grep -v 'The agent has no identities.' | wc -l) -eq 0 ]; then ssh-agent && ssh-add "${sshKeyPath}" ; fi
echo -ne "\033]0;SSH:${tabTitle}\007"
ssh -l ${sshUser} -A $@
